# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-13 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_app', '0002_auto_20171017_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enrollment_number',
            field=models.CharField(default='', max_length=12, unique=True),
        ),
    ]
