# Generated by Django 2.2.1 on 2020-01-06 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c_app', '0003_user_enrollment_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='enrollment_number',
        ),
    ]
